export const urduDictionary = {
  inspire: "حوصلہ افزائی",
  success: "کامیابی",
  achieve: "حاصل کرنا",
  learn: "سیکھنا",
  goal: "ہدف",
  dream: "خواب",
  effort: "کوشش",
  challenge: "چیلنج",
  motivation: "تحریک",
  progress: "ترقی",
  opportunity: "موقع",
  knowledge: "علم",
  skill: "ہنر",
  work: "کام",
  passion: "جذبہ",
  believe: "یقین",
  grow: "بڑھنا",
  strength: "طاقت",
  focus: "توجہ",
  vision: "تصور",
  change: "تبدیلی",
  future: "مستقبل",
  improve: "بہتر کرنا",
  create: "تخلیق کرنا",
  idea: "خیال",
  plan: "منصوبہ",
  action: "عمل",
  result: "نتیجہ",
  team: "ٹیم",
  lead: "قیادت کرنا",
  support: "حمایت",
  trust: "اعتماد",
  value: "قدر",
  respect: "احترام",
  share: "بانٹنا",
  connect: "جڑنا",
  build: "بنाना",
  innovate: "اختراع کرنا",
  solve: "حل کرنا",
  problem: "مسئلہ",
  solution: "حل",
  think: "سوچنا",
  understand: "سمجھنا",
  communicate: "بات چیت کرنا",
  listen: "سننا",
  speak: "بولنا",
  write: "لکھنا",
  read: "پڑھنا",
  explore: "دریافت کرنا",
  discover: "تلاش کرنا",
  journey: "سفر",
  experience: "تجربہ",
  wisdom: "دانائی",
  courage: "ہمت",
  hope: "امید",
  love: "محبت",
  life: "زندگی",
  happiness: "خوشی",
  peace: "امن",
  freedom: "آزادی",
  truth: "سچائی",
  power: "طاقت",
  energy: "توانائی",
  time: "وقت",
  world: "دنیا",
  people: "لوگ",
  community: "برادری",
  culture: "ثقافت",
  tradition: "روایت",
  history: "تاریخ",
  nature: "فطرت",
  environment: "ماحول",
  technology: "ٹیکنالوجی",
  science: "سائنس",
  data: "ڈیٹا",
  information: "معلومات",
  system: "نظام",
  process: "عمل",
  develop: "ترقی کرنا",
  design: "ڈیزائن",
  project: "منصوبہ",
  task: "کام",
  strategy: "حکمت عملی",
  failure: "ناکامی",
  quality: "معیار",
  performance: "کارکردگی",
  efficiency: "کارکردگی",
  effective: "مؤثر",
  impact: "اثر",
  growth: "ترقی",
  innovation: "اختراع",
  creativity: "تخلیقی صلاحیت",
  mission: "مشن",
  purpose: "مقصد",
  collaboration: "تعاون",
  teamwork: "ٹیم ورک",
  leadership: "قیادت",
  management: "انتظام",
  execute: "عمل کرنا",
  dedication: "لگن",
  commitment: "عزم",
  encourage: "حوصلہ دینا",
  help: "مدد",
  talent: "صلاحیت",
  ability: "قابلیت",
  weakness: "کمزوری",
  threat: "خطرہ",
  risk: "خطرہ",
  safety: "حفاظت",
  security: "سلامتی",
  confidence: "اعتماد",
  belief: "یقین",
  faith: "ایمان",
  aspiration: "خواہش",
  target: "ہدف",
  objective: "مقصد",
  step: "قدم",
  development: "ترقی",
  improvement: "بہتری",
  achievement: "کامیابی",
  victory: "فتح",
  obstacle: "رکاوٹ",
  answer: "جواب",
  question: "سوال",
  thought: "خیال",
  concept: "تصور",
  imagination: "تخیل",
  invention: "ایجاد",
  discovery: "دریافت",
  exploration: "تحقیق",
  research: "تحقیق",
  study: "مطالعہ",
  education: "تعلیم",
  intelligence: "ذہانت",
  practice: "مشق",
  job: "ملازمت",
  career: "کیریئر",
  profession: "پیشہ",
  business: "کاروبار",
  industry: "صنعت",
  market: "مارکیٹ",
  product: "پروڈکٹ",
  service: "سروس",
  customer: "صارف",
  client: "کلائنٹ",
  user: "صارف",
  society: "معاشرہ",
  honor: "عزت",
  dignity: "وقار",
};

export async function translateToUrdu(text: string): Promise<string> {
  let translated = text;
  for (const [en, ur] of Object.entries(urduDictionary)) {
    translated = translated.replace(new RegExp(`\\b${en}\\b`, "gi"), ur);
  }
  return translated;
}