export const urduDictionary: Record<string, string> = {
  // Articles and basic words
  "this": "یہ",
  "that": "وہ",
  "these": "یہ",
  "those": "وہ",
  "is": "ہے",
  "are": "ہیں",
  "was": "تھا",
  "were": "تھے",
  "be": "ہونا",
  "been": "تھا",
  "being": "ہونا",
  "a": "ایک",
  "an": "ایک",
  "the": "یہ",
  "of": "کا",
  "in": "میں",
  "on": "پر",
  "at": "میں",
  "to": "کو",
  "for": "کے لیے",
  "with": "کے ساتھ",
  "by": "کے ذریعے",
  "from": "سے",
  "about": "کے بارے میں",
  "into": "میں",
  "through": "کے ذریعے",
  "during": "کے دوران",
  "before": "سے پہلے",
  "after": "کے بعد",
  "above": "اوپر",
  "below": "نیچے",
  "up": "اوپر",
  "down": "نیچے",
  "out": "باہر",
  "off": "بند",
  "over": "اوپر",
  "under": "نیچے",
  "again": "دوبارہ",
  "further": "مزید",
  "then": "پھر",
  "once": "ایک بار",
  
  // Conjunctions
  "and": "اور",
  "or": "یا",
  "but": "لیکن",
  "if": "اگر",
  "while": "جبکہ",
  "because": "کیونکہ",
  "so": "تو",
  "than": "سے",
  "when": "جب",
  "where": "کہاں",
  "why": "کیوں",
  "how": "کیسے",
  
  // Pronouns
  "i": "میں",
  "you": "آپ",
  "he": "وہ",
  "she": "وہ",
  "it": "یہ",
  "we": "ہم",
  "they": "وہ",
  "me": "مجھے",
  "him": "اسے",
  "her": "اسے",
  "us": "ہمیں",
  "them": "انہیں",
  "my": "میرا",
  "your": "آپ کا",
  "his": "اس کا",
  "its": "اس کا",
  "our": "ہمارا",
  "their": "ان کا",
  
  // Common verbs
  "have": "رکھنا",
  "has": "رکھتا ہے",
  "had": "رکھا تھا",
  "do": "کرنا",
  "does": "کرتا ہے",
  "did": "کیا",
  "will": "گا",
  "would": "گا",
  "could": "سک سکتا",
  "should": "چاہیے",
  "may": "شاید",
  "might": "شاید",
  "must": "ضروری",
  "can": "سکنا",
  "make": "بنانا",
  "made": "بنایا",
  "get": "حاصل کرنا",
  "got": "حاصل کیا",
  "give": "دینا",
  "gave": "دیا",
  "take": "لینا",
  "took": "لیا",
  "come": "آنا",
  "came": "آیا",
  "go": "جانا",
  "went": "گیا",
  "see": "دیکھنا",
  "saw": "دیکھا",
  "look": "دیکھنا",
  "know": "جاننا",
  "knew": "جانتا تھا",
  "think": "سوچنا",
  "thought": "سوچا",
  "say": "کہنا",
  "said": "کہا",
  "tell": "بتانا",
  "told": "بتایا",
  "ask": "پوچھنا",
  "asked": "پوچھا",
  "try": "کوشش کرنا",
  "tried": "کوشش کی",
  "use": "استعمال کرنا",
  "used": "استعمال کیا",
  "work": "کام کرنا",
  "worked": "کام کیا",
  "call": "کال کرنا",
  "called": "کال کیا",
  "want": "چاہنا",
  "wanted": "چاہا",
  "need": "ضرورت",
  "needed": "ضرورت تھی",
  "feel": "محسوس کرنا",
  "felt": "محسوس کیا",
  "become": "بننا",
  "became": "بنا",
  "leave": "چھوڑنا",
  "left": "چھوڑا",
  "put": "رکھنا",
  "keep": "رکھنا",
  "let": "دینا",
  "begin": "شروع کرنا",
  "began": "شروع کیا",
  "seem": "لگنا",
  "seemed": "لگا",
  "help": "مدد کرنا",
  "helped": "مدد کی",
  "show": "دکھانا",
  "showed": "دکھایا",
  "hear": "سننا",
  "heard": "سنا",
  "play": "کھیلنا",
  "played": "کھیلا",
  "run": "دوڑنا",
  "ran": "دوڑا",
  "move": "حرکت کرنا",
  "moved": "حرکت کی",
  "live": "رہنا",
  "lived": "رہا",
  "bring": "لانا",
  "brought": "لایا",
  "happen": "ہونا",
  "happened": "ہوا",
  "write": "لکھنا",
  "wrote": "لکھا",
  "sit": "بیٹھنا",
  "sat": "بیٹھا",
  "stand": "کھڑا ہونا",
  "stood": "کھڑا ہوا",
  "lose": "کھونا",
  "lost": "کھویا",
  "pay": "ادائیگی کرنا",
  "paid": "ادائیگی کی",
  "meet": "ملنا",
  "met": "ملا",
  "include": "شامل کرنا",
  "included": "شامل کیا",
  "continue": "جاری رکھنا",
  "continued": "جاری رکھا",
  "set": "سیٹ کرنا",
  "learn": "سیکھنا",
  "learned": "سیکھا",
  "change": "تبدیل کرنا",
  "changed": "تبدیل کیا",
  "lead": "رہنمائی کرنا",
  "led": "رہنمائی کی",
  "understand": "سمجھنا",
  "understood": "سمجھا",
  "watch": "دیکھنا",
  "watched": "دیکھا",
  "follow": "فالو کرنا",
  "followed": "فالو کیا",
  "stop": "رکنا",
  "stopped": "رکا",
  "create": "بنانا",
  "created": "بنایا",
  "speak": "بولنا",
  "spoke": "بولا",
  "read": "پڑھنا",
  "allow": "اجازت دینا",
  "allowed": "اجازت دی",
  "add": "شامل کرنا",
  "added": "شامل کیا",
  "spend": "خرچ کرنا",
  "spent": "خرچ کیا",
  "grow": "بڑھنا",
  "grew": "بڑھا",
  "open": "کھولنا",
  "opened": "کھولا",
  "walk": "چلنا",
  "walked": "چلا",
  "win": "جیتنا",
  "won": "جیتا",
  "offer": "پیشکش کرنا",
  "offered": "پیشکش کی",
  "remember": "یاد رکھنا",
  "remembered": "یاد رکھا",
  "love": "محبت کرنا",
  "loved": "محبت کی",
  "consider": "غور کرنا",
  "considered": "غور کیا",
  "appear": "ظاہر ہونا",
  "appeared": "ظاہر ہوا",
  "buy": "خریدنا",
  "bought": "خریدا",
  "wait": "انتظار کرنا",
  "waited": "انتظار کیا",
  "serve": "خدمت کرنا",
  "served": "خدمت کی",
  "die": "مرنا",
  "died": "مرا",
  "send": "بھیجنا",
  "sent": "بھیجا",
  "expect": "توقع کرنا",
  "expected": "توقع کی",
  "build": "بنانا",
  "built": "بنایا",
  "stay": "رہنا",
  "stayed": "رہا",
  "fall": "گرنا",
  "fell": "گرا",
  "cut": "کاٹنا",
  "reach": "پہنچنا",
  "reached": "پہنچا",
  "kill": "مارنا",
  "killed": "مارا",
  "remain": "باقی رہنا",
  "remained": "باقی رہا",
  "suggest": "تجویز کرنا",
  "suggested": "تجویز کی",
  "raise": "اٹھانا",
  "raised": "اٹھایا",
  "pass": "پاس کرنا",
  "passed": "پاس کیا",
  "sell": "بیچنا",
  "sold": "بیچا",
  "require": "ضرورت ہونا",
  "required": "ضرورت تھی",
  "report": "رپورٹ کرنا",
  "reported": "رپورٹ کی",
  "decide": "فیصلہ کرنا",
  "decided": "فیصلہ کیا",
  "pull": "کھینچنا",
  "pulled": "کھینچا",

  // Common nouns
  "people": "لوگ",
  "person": "شخص",
  "man": "آدمی",
  "woman": "عورت",
  "child": "بچہ",
  "children": "بچے",
  "boy": "لڑکا",
  "girl": "لڑکی",
  "family": "خاندان",
  "friend": "دوست",
  "group": "گروپ",
  "team": "ٹیم",
  "company": "کمپنی",
  "business": "کاروبار",
  "government": "حکومت",
  "country": "ملک",
  "state": "ریاست",
  "city": "شہر",
  "town": "قصبہ",
  "area": "علاقہ",
  "community": "کمیونٹی",
  "world": "دنیا",
  "place": "جگہ",
  "home": "گھر",
  "house": "مکان",
  "room": "کمرہ",
  "office": "دفتر",
  "school": "سکول",
  "university": "یونیورسٹی",
  "college": "کالج",
  "hospital": "ہسپتال",
  "church": "چرچ",
  "market": "بازار",
  "store": "دکان",
  "restaurant": "ریستوراں",
  "hotel": "ہوٹل",
  "car": "گاڑی",
  "bus": "بس",
  "train": "ریل گاڑی",
  "plane": "ہوائی جہاز",
  "ship": "جہاز",
  "road": "سڑک",
  "street": "گلی",
  "way": "راستہ",
  "door": "دروازہ",
  "window": "کھڑکی",
  "table": "میز",
  "chair": "کرسی",
  "bed": "بستر",
  "book": "کتاب",
  "paper": "کاغذ",
  "pen": "قلم",
  "computer": "کمپیوٹر",
  "phone": "فون",
  "internet": "انٹرنیٹ",
  "website": "ویب سائٹ",
  "email": "ای میل",
  "message": "پیغام",
  "news": "خبریں",
  "information": "معلومات",
  "data": "ڈیٹا",
  "technology": "ٹیکنالوجی",
  "science": "سائنس",
  "research": "تحقیق",
  "study": "مطالعہ",
  "education": "تعلیم",
  "health": "صحت",
  "medicine": "دوا",
  "food": "کھانا",
  "water": "پانی",
  "air": "ہوا",
  "fire": "آگ",
  "earth": "زمین",
  "sun": "سورج",
  "moon": "چاند",
  "star": "ستارہ",
  "sky": "آسمان",
  "weather": "موسم",
  "rain": "بارش",
  "snow": "برف",
  "wind": "ہوا",
  "tree": "درخت",
  "flower": "پھول",
  "animal": "جانور",
  "dog": "کتا",
  "cat": "بلی",
  "bird": "پرندہ",
  "fish": "مچھلی",
  "time": "وقت",
  "day": "دن",
  "night": "رات",
  "morning": "صبح",
  "afternoon": "دوپہر",
  "evening": "شام",
  "week": "ہفتہ",
  "month": "مہینہ",
  "year": "سال",
  "hour": "گھنٹہ",
  "minute": "منٹ",
  "second": "سیکنڈ",
  "today": "آج",
  "tomorrow": "کل",
  "yesterday": "کل",
  "money": "پیسہ",
  "dollar": "ڈالر",
  "price": "قیمت",
  "cost": "لاگت",
  "job": "نوکری",
  "worker": "کارکن",
  "service": "خدمت",
  "product": "پروڈکٹ",
  "customer": "صارف",
  "client": "کلائنٹ",
  "project": "پروجیکٹ",
  "program": "پروگرام",
  "system": "نظام",
  "process": "عمل",
  "method": "طریقہ",
  "problem": "مسئلہ",
  "issue": "مسئلہ",
  "question": "سوال",
  "answer": "جواب",
  "solution": "حل",
  "result": "نتیجہ",
  "effect": "اثر",
  "cause": "وجہ",
  "reason": "وجہ",
  "idea": "خیال",
  "mind": "دماغ",
  "body": "جسم",
  "head": "سر",
  "face": "چہرہ",
  "eye": "آنکھ",
  "hand": "ہاتھ",
  "foot": "پاؤں",
  "heart": "دل",
  "life": "زندگی",
  "death": "موت",
  "pain": "درد",
  "peace": "امن",
  "war": "جنگ",
  "power": "طاقت",
  "energy": "توانائی",
  "force": "قوت",
  "nature": "فطرت",
  "music": "موسیقی",
  "art": "فن",
  "culture": "ثقافت",
  "history": "تاریخ",
  "future": "مستقبل",
  "past": "ماضی",
  "present": "حال",
  "law": "قانون",
  "rule": "اصول",
  "policy": "پالیسی",
  "politics": "سیاست",
  "society": "معاشرہ",
  "social": "سماجی",
  "economic": "اقتصادی",
  "financial": "مالی",
  "personal": "ذاتی",
  "public": "عوامی",
  "private": "نجی",
  "national": "قومی",
  "international": "بین الاقوامی",
  "global": "عالمی",
  "local": "مقامی",
  "regional": "علاقائی",
  "human": "انسان",
  "natural": "قدرتی",
  "physical": "جسمانی",
  "mental": "ذہنی",
  "spiritual": "روحانی",
  "material": "مادی",
  "digital": "ڈیجیٹل",
  "online": "آن لائن",
  "offline": "آف لائن",
  "virtual": "ورچوئل",
  "real": "حقیقی",
  "true": "سچ",
  "false": "جھوٹ",
  "fact": "حقیقت",
  "opinion": "رائے",
  "belief": "عقیدہ",
  "faith": "ایمان",
  "hope": "امید",
  "dream": "خواب",
  "goal": "مقصد",
  "plan": "منصوبہ",
  "strategy": "حکمت عملی",
  "decision": "فیصلہ",
  "choice": "انتخاب",
  "option": "آپشن",
  "chance": "موقع",
  "opportunity": "موقع",
  "possibility": "امکان",
  "ability": "صلاحیت",
  "skill": "مہارت",
  "talent": "ٹیلنٹ",
  "experience": "تجربہ",
  "knowledge": "علم",
  "wisdom": "حکمت",
  "understanding": "سمجھ",
  "learning": "سیکھنا",
  "teaching": "تدریس",
  "training": "تربیت",
  "development": "ترقی",
  "growth": "نمو",
  "improvement": "بہتری",
  "progress": "ترقی",
  "success": "کامیابی",
  "failure": "ناکامی",
  "achievement": "کامیابی",
  "victory": "فتح",
  "defeat": "شکست",
  "loss": "نقصان",
  "gain": "فائدہ",
  "benefit": "فائدہ",
  "advantage": "فائدہ",
  "disadvantage": "نقصان",
  "risk": "خطرہ",
  "danger": "خطرہ",
  "safety": "حفاظت",
  "security": "سلامتی",
  "protection": "تحفظ",
  "support": "مدد",
  "assistance": "امداد",
  "aid": "امداد",
  "advice": "مشورہ",
  "guidance": "رہنمائی",
  "direction": "سمت",
  "leadership": "قیادت",
  "management": "انتظام",
  "control": "کنٹرول",
  "authority": "اختیار",
  "responsibility": "ذمہ داری",
  "duty": "فرض",
  "obligation": "پابندی",
  "commitment": "عہد",
  "promise": "وعدہ",
  "agreement": "معاہدہ",
  "contract": "کنٹریکٹ",
  "deal": "معاملہ",
  "relationship": "رشتہ",
  "connection": "کنکشن",
  "link": "لنک",
  "bond": "بانڈ",
  "tie": "ٹائی",
  "partnership": "شراکت",
  "cooperation": "تعاون",
  "collaboration": "تعاون",
  "communication": "رابطہ",
  "conversation": "گفتگو",
  "discussion": "بحث",
  "meeting": "میٹنگ",
  "conference": "کانفرنس",
  "presentation": "پیش کش",
  "speech": "تقریر",
  "talk": "بات",
  "word": "لفظ",
  "language": "زبان",
  "voice": "آواز",
  "sound": "آواز",
  "noise": "شور",
  "silence": "خاموشی",
  "quiet": "خاموش",
  "loud": "بلند آواز",
  "soft": "نرم",
  "hard": "سخت",
  "strong": "مضبوط",
  "weak": "کمزور",
  "heavy": "بھاری",
  "light": "ہلکا",
  "thick": "موٹا",
  "thin": "پتلا",
  "wide": "چوڑا",
  "narrow": "تنگ",
  "long": "لمبا",
  "short": "چھوٹا",
  "tall": "لمبا",
  "high": "اعلیٰ",
  "low": "کم",
  "deep": "گہرا",
  "shallow": "اتھلا",
  "full": "بھرا ہوا",
  "empty": "خالی",
  "complete": "مکمل",
  "incomplete": "نامکمل",
  "perfect": "کامل",
  "imperfect": "ناکامل",
  "whole": "پورا",
  "part": "حصہ",
  "piece": "ٹکڑا",
  "section": "حصہ",
  "portion": "حصہ",
  "share": "شیئر",
  "total": "کل",
  "amount": "رقم",
  "number": "نمبر",
  "count": "گنتی",
  "quantity": "مقدار",
  "quality": "معیار",
  "level": "سطح",
  "degree": "ڈگری",
  "rate": "شرح",
  "speed": "رفتار",
  "pace": "رفتار",
  "scale": "پیمانہ",
  "size": "سائز",
  "length": "لمبائی",
  "width": "چوڑائی",
  "height": "اونچائی",
  "depth": "گہرائی",
  "weight": "وزن",
  "mass": "بڑے پیمانے پر",
  "volume": "حجم",
  "capacity": "صلاحیت",
  "space": "جگہ",
  "region": "علاقہ",
  "zone": "زون",
  "territory": "علاقہ",
  "land": "زمین",
  "ground": "زمین",
  "soil": "مٹی",
  "field": "کھیت",
  "farm": "فارم",
  "garden": "باغ",
  "park": "پارک",
  "forest": "جنگل",
  "mountain": "پہاڑ",
  "hill": "پہاڑی",
  "valley": "وادی",
  "river": "دریا",
  "lake": "جھیل",
  "sea": "سمندر",
  "ocean": "سمندر",
  "beach": "ساحل",
  "island": "جزیرہ",
  "desert": "صحرا",
  "climate": "آب و ہوا",
  "temperature": "درجہ حرارت",
  "heat": "گرمی",
  "cold": "سردی",
  "warm": "گرم",
  "cool": "ٹھنڈا",
  "hot": "گرم",
  "freezing": "منجمد",
  "ice": "برف",
  "steam": "بھاپ",
  "gas": "گیس",
  "liquid": "مائع",
  "solid": "ٹھوس",
  "metal": "دھات",
  "wood": "لکڑی",
  "stone": "پتھر",
  "glass": "شیشہ",
  "plastic": "پلاسٹک",
  "cloth": "کپڑا",
  "leather": "چمڑا",
  "rubber": "ربڑ",
  "oil": "تیل",
  "fuel": "ایندھن",
  "electricity": "بجلی",
  "battery": "بیٹری",
  "machine": "مشین",
  "engine": "انجن",
  "motor": "موٹر",
  "device": "آلہ",
  "tool": "اوزار",
  "equipment": "سامان",
  "instrument": "آلہ",
  "weapon": "ہتھیار",
  "gun": "بندوق",
  "knife": "چاقو",
  "sword": "تلوار",
  "shield": "ڈھال",
  "armor": "بکتر",
  "clothes": "کپڑے",
  "shirt": "قمیض",
  "pants": "پتلون",
  "dress": "لباس",
  "shoe": "جوتا",
  "hat": "ٹوپی",
  "coat": "کوٹ",
  "jacket": "جیکٹ",
  "bag": "بیگ",
  "box": "ڈبہ",
  "bottle": "بوتل",
  "cup": "کپ",
  "plate": "پلیٹ",
  "bowl": "کٹورا",
  "spoon": "چمچ",
  "fork": "کانٹا",
  "key": "چابی",
  "lock": "تالا",
  "chain": "زنجیر",
  "rope": "رسی",
  "string": "تار",
  "wire": "تار",
  "cable": "کیبل",
  "bridge": "پل",
  "building": "عمارت",
  "structure": "ڈھانچہ",
  "wall": "دیوار",
  "floor": "فرش",
  "ceiling": "چھت",
  "roof": "چھت",
  "stairs": "سیڑھیاں",
  "elevator": "لفٹ",
  "lift": "لفٹ",

  // Adjectives
  "good": "اچھا",
  "bad": "برا",
  "great": "عظیم",
  "small": "چھوٹا",
  "big": "بڑا",
  "large": "بڑا",
  "huge": "بہت بڑا",
  "tiny": "ننھا",
  "new": "نیا",
  "old": "پرانا",
  "young": "جوان",
  "fresh": "تازہ",
  "clean": "صاف",
  "dirty": "گندا",
  "pure": "خالص",
  "clear": "صاف",
  "bright": "روشن",
  "dark": "تاریک",
  "easy": "آسان",
  "difficult": "مشکل",
  "simple": "آسان",
  "complex": "پیچیدہ",
  "complicated": "پیچیدہ",
  "fast": "تیز",
  "quick": "تیز",
  "slow": "آہستہ",
  "early": "جلدی",
  "late": "دیر",
  "ready": "تیار",
  "busy": "مصروف",
  "free": "آزاد",
  "available": "دستیاب",
  "closed": "بند",
  "active": "فعال",
  "passive": "غیر فعال",
  "positive": "مثبت",
  "negative": "منفی",
  "right": "درست",
  "correct": "درست",
  "wrong": "غلط",
  "accurate": "درست",
  "exact": "عین",
  "precise": "درست",
  "sure": "یقین",
  "certain": "یقینی",
  "possible": "ممکن",
  "impossible": "ناممکن",
  "necessary": "ضروری",
  "important": "اہم",
  "significant": "اہم",
  "serious": "سنجیدہ",
  "common": "عام",
  "rare": "نایاب",
  "special": "خاص",
  "unique": "منفرد",
  "normal": "عام",
  "strange": "عجیب",
  "different": "مختلف",
  "same": "وہی",
  "similar": "ملتا جلتا",
  "equal": "برابر",
  "fair": "منصفانہ",
  "unfair": "ناانصافی",
  "honest": "ایماندار",
  "dishonest": "بے ایمان",
  "loyal": "وفادار",
  "faithful": "ایماندار",
  "reliable": "قابل اعتماد",
  "trustworthy": "قابل اعتماد",
  "responsible": "ذمہ دار",
  "careful": "احتیاط",
  "careless": "لاپرواہ",
  "safe": "محفوظ",
  "dangerous": "خطرناک",
  "risky": "خطرناک",
  "secure": "محفوظ",
  "comfortable": "آرام دہ",
  "uncomfortable": "بے آرام",
  "pleasant": "خوشگوار",
  "unpleasant": "ناخوشگوار",
  "nice": "اچھا",
  "beautiful": "خوبصورت",
  "pretty": "خوبصورت",
  "ugly": "بدصورت",
  "attractive": "پرکشش",
  "handsome": "خوبصورت",
  "lovely": "پیارا",
  "wonderful": "شاندار",
  "amazing": "حیرت انگیز",
  "excellent": "بہترین",
  "fantastic": "شاندار",
  "awesome": "شاندار",
  "terrible": "خوفناک",
  "awful": "خوفناک",
  "horrible": "خوفناک",
  "disgusting": "نفرت انگیز",
  "delicious": "لذیذ",
  "tasty": "لذیذ",
  "sweet": "میٹھا",
  "sour": "کھٹا",
  "bitter": "کڑوا",
  "salty": "نمکین",
  "spicy": "مسالہ دار",
  "mild": "ہلکا",
  "powerful": "طاقتور",
  "gentle": "نرم",
  "rough": "کھردرا",
  "smooth": "ہموار",
  "sharp": "تیز",
  "dull": "کند",
  "flat": "چپٹا",
  "round": "گول",
  "square": "مربع",
  "straight": "سیدھا",
  "curved": "خمیدہ",
  "bent": "موڑا ہوا",
  "broken": "ٹوٹا ہوا",
  "fixed": "ٹھیک",
  "damaged": "خراب",
  "healthy": "صحت مند",
  "sick": "بیمار",
  "ill": "بیمار",
  "well": "اچھا",
  "fine": "ٹھیک",
  "tired": "تھکا ہوا",
  "rested": "آرام کیا ہوا",
  "sleepy": "نیند آنا",
  "awake": "جاگنا",
  "alive": "زندہ",
  "dead": "مردہ",
  "born": "پیدا ہوا",
  "married": "شادی شدہ",
  "single": "اکیلا",
  "divorced": "طلاق یافتہ",
  "happy": "خوش",
  "sad": "اداس",
  "angry": "غصہ",
  "mad": "پاگل",
  "excited": "پرجوش",
  "calm": "پرسکون",
  "nervous": "گھبرایا ہوا",
  "worried": "پریشان",
  "afraid": "خوف زدہ",
  "scared": "ڈرا ہوا",
  "brave": "بہادر",
  "confident": "اعتماد",
  "proud": "فخر",
  "ashamed": "شرمندہ",
  "guilty": "مجرم",
  "innocent": "بے گناہ",
  "lucky": "خوش قسمت",
  "unlucky": "بدقسمت",
  "successful": "کامیاب",
  "famous": "مشہور",
  "popular": "مقبول",
  "rich": "امیر",
  "wealthy": "دولت مند",
  "poor": "غریب",
  "cheap": "سستا",
  "expensive": "مہنگا",
  "valuable": "قیمتی",
  "worthless": "بے قیمت",
  "useful": "مفید",
  "useless": "بے کار",
  "helpful": "مددگار",
  "harmful": "نقصان دہ",
  "kind": "مہربان",
  "cruel": "ظالم",
  "generous": "سخی",
  "selfish": "خودغرض",
  "polite": "مہذب",
  "rude": "بدتمیز",
  "friendly": "دوستانہ",
  "unfriendly": "غیر دوستانہ",
  "patient": "صبر",
  "impatient": "بے صبر",
  "lazy": "سست",
  "hardworking": "محنتی",
  "smart": "ہوشیار",
  "intelligent": "ذہین",
  "clever": "چالاک",
  "wise": "حکیم",
  "foolish": "بے وقوف",
  "stupid": "احمق",
  "crazy": "پاگل",
  "funny": "مزاحیہ",
  "interesting": "دلچسپ",
  "boring": "بورنگ",
  "exciting": "دلچسپ",
  "surprising": "حیرت انگیز",
  "unexpected": "غیر متوقع",
  "sudden": "اچانک",
  "gradual": "بتدریج",
  "immediate": "فوری",
  "instant": "فوری",
  "rapid": "تیز",
  "steady": "مستحکم",
  "stable": "مستحکم",
  "unstable": "غیر مستحکم",
  "firm": "مضبوط",
  "tough": "سخت",
  "tender": "نرم",
  "flexible": "لچکدار",
  "stiff": "سخت",
  "loose": "ڈھیلا",
  "tight": "تنگ",
  "broad": "چوڑا",
  "brief": "مختصر",
  "permanent": "مستقل",
  "temporary": "عارضی",
  "final": "حتمی",
  "partial": "جزوی",
  "blank": "خالی",
  "filled": "بھرا ہوا",
  "crowded": "بھیڑ",
  "silent": "خاموش",
  "noisy": "شور",
  "unclear": "غیر واضح",
  "obvious": "واضح",
  "hidden": "چھپا ہوا",
  "visible": "نظر آنے والا",
  "invisible": "نظر نہ آنے والا",
  "individual": "انفرادی",
  "general": "عام",
  "specific": "مخصوص",
  "particular": "خاص",
  "approximate": "تقریبی",
  "close": "قریب",
  "near": "پاس",
  "far": "دور",
  "distant": "دور",
  "foreign": "غیر ملکی",
  "domestic": "گھریلو",
  "universal": "آفاقی",
  "federal": "وفاقی",
  "urban": "شہری",
  "rural": "دیہاتی",
  "modern": "جدید",
  "traditional": "روایتی",
  "classical": "کلاسیکی",
  "ancient": "قدیم",
  "medieval": "قرون وسطیٰ",
  "contemporary": "معاصر",
  "current": "موجودہ",
  "previous": "پچھلا",
  "former": "سابق",
  "recent": "حالیہ",
  "latest": "تازہ ترین",
  "original": "اصل",
  "fake": "جعلی",
  "artificial": "مصنوعی",
  "actual": "اصل",
  "theoretical": "نظریاتی",
  "practical": "عملی",
  "technical": "تکنیکی",
  "scientific": "سائنسی",
  "medical": "طبی",
  "legal": "قانونی",
  "illegal": "غیر قانونی",
  "official": "سرکاری",
  "unofficial": "غیر سرکاری",
  "formal": "رسمی",
  "informal": "غیر رسمی",
  "casual": "غیر رسمی",
  "professional": "پیشہ ورانہ",
  "amateur": "شوقیہ",
  "expert": "ماہر",
  "skilled": "ہنر مند",
  "experienced": "تجربہ کار",
  "qualified": "اہل",
  "trained": "تربیت یافتہ",
  "educated": "تعلیم یافتہ",
  "literate": "پڑھا لکھا",
  "illiterate": "ان پڑھ",

  // Numbers and quantities
  "one": "ایک",
  "two": "دو",
  "three": "تین",
  "four": "چار",
  "five": "پانچ",
  "six": "چھ",
  "seven": "سات",
  "eight": "آٹھ",
  "nine": "نو",
  "ten": "دس",
  "eleven": "گیارہ",
  "twelve": "بارہ",
  "thirteen": "تیرہ",
  "fourteen": "چودہ",
  "fifteen": "پندرہ",
  "sixteen": "سولہ",
  "seventeen": "سترہ",
  "eighteen": "اٹھارہ",
  "nineteen": "انیس",
  "twenty": "بیس",
  "thirty": "تیس",
  "forty": "چالیس",
  "fifty": "پچاس",
  "sixty": "ساٹھ",
  "seventy": "ستر",
  "eighty": "اسی",
  "ninety": "نوے",
  "hundred": "سو",
  "thousand": "ہزار",
  "million": "دس لاکھ",
  "billion": "ارب",
  "first": "پہلا",
  "third": "تیسرا",
  "fourth": "چوتھا",
  "fifth": "پانچواں",
  "sixth": "چھٹا",
  "seventh": "ساتواں",
  "eighth": "آٹھواں",
  "ninth": "نواں",
  "tenth": "دسواں",
  "last": "آخری",
  "next": "اگلا",
  "another": "دوسرا",
  "other": "دوسرا",
  "others": "دوسرے",
  "both": "دونوں",
  "either": "یا تو",
  "neither": "نہ تو",
  "each": "ہر ایک",
  "every": "ہر",
  "all": "تمام",
  "some": "کچھ",
  "any": "کوئی",
  "many": "بہت سارے",
  "much": "بہت",
  "more": "زیادہ",
  "most": "سب سے زیادہ",
  "less": "کم",
  "least": "کم سے کم",
  "few": "کچھ",
  "little": "تھوڑا",
  "several": "کئی",
  "enough": "کافی",
  "too": "بہت",
  "very": "بہت",
  "quite": "کافی",
  "rather": "بلکہ",
  "almost": "تقریباً",
  "nearly": "تقریباً",
  "around": "کے ارد گرد",
  "approximately": "تقریباً",
  "exactly": "بالکل",
  "precisely": "بالکل",
  "roughly": "تقریباً",
  "mainly": "بنیادی طور پر",
  "mostly": "زیادہ تر",
  "generally": "عام طور پر",
  "usually": "عام طور پر",
  "normally": "عام طور پر",
  "typically": "عام طور پر",
  "often": "اکثر",
  "frequently": "اکثر",
  "sometimes": "کبھی کبھی",
  "occasionally": "کبھی کبھار",
  "rarely": "شاذ و نادر",
  "seldom": "شاذ و نادر",
  "hardly": "مشکل سے",
  "never": "کبھی نہیں",
  "always": "ہمیشہ",
  "forever": "ہمیشہ کے لیے",
  "constantly": "مستقل",
  "continuously": "مسلسل",
  "regularly": "باقاعدگی سے",
  "daily": "روزانہ",
  "weekly": "ہفتہ وار",
  "monthly": "ماہانہ",
  "yearly": "سالانہ",
  "annually": "سالانہ",
  "immediately": "فوری طور پر",
  "instantly": "فوری طور پر",
  "suddenly": "اچانک",
  "quickly": "جلدی سے",
  "rapidly": "تیزی سے",
  "slowly": "آہستہ آہستہ",
  "gradually": "بتدریج",
  "eventually": "آخر کار",
  "finally": "آخر میں",
  "recently": "حال ہی میں",
  "lately": "حال ہی میں",
  "currently": "فی الوقت",
  "presently": "فی الوقت",
  "now": "اب",
  "tonight": "آج رات",
  "ago": "پہلے",
  "since": "جب سے",
  "until": "تک",
  "till": "تک",
  "meanwhile": "اس دوران",
  "already": "پہلے سے ہی",
  "yet": "ابھی تک",
  "still": "اب بھی",
  "just": "بس",
  "only": "صرف",
  "even": "یہاں تک کہ",
  "also": "بھی",
  "nor": "نہ ہی",
  "not": "نہیں",
  "no": "نہیں",
  "yes": "ہاں",
  "ok": "ٹھیک ہے",
  "okay": "ٹھیک ہے",
  "certainly": "یقیناً",
  "definitely": "یقیناً",
  "absolutely": "بالکل",
  "probably": "شاید",
  "possibly": "ممکن ہے",
  "maybe": "شاید",
  "perhaps": "شاید",
  "hopefully": "امید ہے",
  "unfortunately": "بدقسمتی سے",
  "luckily": "خوش قسمتی سے",
  "fortunately": "خوش قسمتی سے",

  // Days of the week
  "monday": "پیر",
  "tuesday": "منگل",
  "wednesday": "بدھ",
  "thursday": "جمعرات",
  "friday": "جمعہ",
  "saturday": "ہفتہ",
  "sunday": "اتوار",

  // Months
  "january": "جنوری",
  "february": "فروری",
  "march": "مارچ",
  "april": "اپریل",
  "june": "جون",
  "july": "جولائی",
  "august": "اگست",
  "september": "ستمبر",
  "october": "اکتوبر",
  "november": "نومبر",
  "december": "دسمبر",

  // Colors
  "red": "سرخ",
  "blue": "نیلا",
  "green": "سبز",
  "yellow": "پیلا",
  "orange": "نارنجی",
  "purple": "جامنی",
  "pink": "گلابی",
  "brown": "بھورا",
  "black": "کالا",
  "white": "سفید",
  "gray": "سرمئی",
  "grey": "سرمئی",
  "gold": "سونا",
  "silver": "چاندی",

  // Blog and content related terms
  "blog": "بلاگ",
  "post": "پوسٹ",
  "article": "مضمون",
  "content": "مواد",
  "text": "متن",
  "paragraph": "پیرا گراف",
  "sentence": "جملہ",
  "title": "عنوان",
  "heading": "سرخی",
  "author": "مصنف",
  "writer": "لکھاری",
  "reader": "قاری",
  "comment": "تبصرہ",
  "like": "پسند کرنا",
  "subscribe": "سبسکرائب کرنا",
  "publish": "شائع کرنا",
  "edit": "ترمیم کرنا",
  "delete": "حذف کرنا",
  "save": "محفوظ کرنا",
  "search": "تلاش کرنا",
  "find": "تلاش کرنا",
  "category": "کیٹگری",
  "tag": "ٹیگ",
  "topic": "موضوع",
  "subject": "موضوع",
  "theme": "موضوع",
  "summary": "خلاصہ",
  "overview": "جائزہ",
  "review": "جائزہ",
  "analysis": "تجزیہ",
  "story": "کہانی",
  "narrative": "بیانیہ",
  "description": "تفصیل",
  "explanation": "وضاحت",
  "definition": "تعریف",
  "example": "مثال",
  "case": "معاملہ",
  "survey": "سروے",
  "interview": "انٹرویو",
  "debate": "بحث",
  "argument": "دلیل",
  "point": "نکتہ",
  "view": "نظریہ",
  "perspective": "نقطہ نظر",
  "approach": "نقطہ نظر",
  "technique": "تکنیک",
  "objective": "مقصد",
  "purpose": "مقصد",
  "aim": "مقصد",
  "target": "ہدف",
  "focus": "توجہ",
  "attention": "توجہ",
  "interest": "دلچسپی",
  "concern": "تشویش",
  "challenge": "چیلنج",
  "difficulty": "مشکل",
  "obstacle": "رکاوٹ",
  "barrier": "رکاوٹ",
  "limit": "حد",
  "boundary": "حد",
  "range": "رینج",
  "scope": "دائرہ",
  "extent": "حد",
  "stage": "مرحلہ",
  "phase": "مرحلہ",
  "step": "قدم",
  "procedure": "طریقہ کار",
  "operation": "آپریشن",
  "function": "فنکشن",
  "role": "کردار",
  "position": "پوزیشن",
  "status": "حیثیت",
  "condition": "حالت",
  "situation": "صورتحال",
  "circumstance": "حالات",
  "context": "تناظر",
  "background": "پس منظر",
  "setting": "ترتیب",
  "environment": "ماحول",
  "atmosphere": "ماحول",
  "tradition": "روایت",
  "custom": "رواج",
  "habit": "عادت",
  "behavior": "رفتار",
  "conduct": "طرز عمل",
  "action": "عمل",
  "activity": "سرگرمی",
  "movement": "تحریک",
  "motion": "حرکت",
  "shift": "تبدیلی",
  "transformation": "تبدیلی",
  "evolution": "ارتقاء",
  "advancement": "ترقی",
  "enhancement": "بہتری",
  "upgrade": "اپ گریڈ",
  "update": "اپ ڈیٹ",
  "revision": "نظرثانی",
  "modification": "تبدیلی",
  "adjustment": "ایڈجسٹمنٹ",
  "adaptation": "موافقت",
  "response": "جواب",
  "reaction": "ردعمل",
  "feedback": "فیڈبیک",
  "input": "ان پٹ",
  "output": "آؤٹ پٹ",
  "outcome": "نتیجہ",
  "consequence": "نتیجہ",
  "impact": "اثر",
  "influence": "اثر",
  "factor": "عنصر",
  "element": "عنصر",
  "component": "جزو",
  "ingredient": "جزو",
  "feature": "خصوصیت",
  "characteristic": "خصوصیت",
  "property": "خاصیت",
  "attribute": "خاصیت",
  "trait": "خاصیت",
  "aspect": "پہلو",
  "dimension": "پہلو",
  "side": "طرف",
  "angle": "زاویہ",
  "orientation": "رخ",
  "location": "مقام",
  "spot": "جگہ",
  "site": "سائٹ",
  "venue": "مقام",
  "destination": "منزل",
  "source": "ذریعہ",
  "origin": "اصل",
  "beginning": "شروعات",
  "start": "شروع",
  "end": "اختتام",
  "finish": "ختم",
  "conclusion": "اختتام",
  "accomplishment": "کامیابی",
  "triumph": "کامیابی",
  "profit": "منافع",
  "potential": "صلاحیت",
  "capability": "صلاحیت",
  "gift": "تحفہ",
  "strength": "طاقت",
  "effort": "کوشش",
  "attempt": "کوشش",
  "trial": "آزمائش",
  "test": "ٹیسٹ",
  "exam": "امتحان",
  "examination": "امتحان",
  "check": "چیک",
  "inspection": "معائنہ",
  "evaluation": "تشخیص",
  "assessment": "تشخیص",
  "judgment": "فیصلہ",
  "selection": "انتخاب",
  "alternative": "متبادل",
  "substitute": "متبادل",
  "replacement": "متبادل",
  "exchange": "تبادلہ",
  "trade": "تجارت",
  "commerce": "تجارت",
  "industry": "صنعت",
  "sector": "شعبہ",
  "domain": "ڈومین",
  "district": "ضلع",
  "province": "صوبہ",
  "nation": "قوم",
  "organization": "تنظیم",
  "institution": "ادارہ",
  "corporation": "کارپوریشن",
  "agency": "ایجنسی",
  "department": "شعبہ",
  "division": "ڈویژن",
  "unit": "یونٹ",
  "branch": "برانچ",
  "center": "مرکز",
  "centre": "مرکز",
  "headquarters": "ہیڈکوارٹر",
  "base": "بیس",
  "foundation": "بنیاد",
  "platform": "پلیٹ فارم",
  "surface": "سطح",
  "top": "اوپر",
  "bottom": "نیچے",
  "middle": "درمیان",
  "edge": "کنارہ",
  "border": "سرحد",
  "line": "لائن",
  "row": "قطار",
  "column": "کالم",
  "list": "فہرست",
  "menu": "مینو",
  "index": "انڈکس",
  "chart": "چارٹ",
  "graph": "گراف",
  "diagram": "ڈایاگرام",
  "picture": "تصویر",
  "image": "تصویر",
  "photo": "فوٹو",
  "photograph": "تصویر",
  "drawing": "ڈرائنگ",
  "painting": "پینٹنگ",
  "design": "ڈیزائن",
  "pattern": "پیٹرن",
  "style": "انداز",
  "fashion": "فیشن",
  "trend": "ٹرینڈ",
  "mode": "موڈ",
  "form": "شکل",
  "shape": "شکل",
  "measure": "پیمانہ",
  "measurement": "پیمائش",
  "distance": "فاصلہ",
  "thickness": "موٹائی",
  "gap": "خلا",
  "hole": "سوراخ",
  "opening": "کھلنا",
  "entrance": "داخلہ",
  "exit": "باہر نکلنا",
  "gate": "گیٹ",
  "path": "راستہ",
  "avenue": "ایونیو",
  "highway": "شاہراہ",
  "route": "راستہ",
  "journey": "سفر",
  "trip": "سفر",
  "travel": "سفر",
  "tour": "دورہ",
  "visit": "دورہ",
  "vacation": "چھٹی",
  "holiday": "چھٹی",
  "break": "وقفہ",
  "rest": "آرام",
  "sleep": "نیند",
  "wake": "جاگنا",
  "noon": "دوپہر",
  "midnight": "آدھی رات",
  "dawn": "فجر",
  "sunrise": "طلوع آفتاب",
  "sunset": "غروب آفتاب",
  "frozen": "منجمد",
  "storm": "طوفان",
  "breeze": "ہوا",
  "cloud": "بادل",
  "planet": "سیارہ",
  "universe": "کائنات",
  "wild": "جنگلی",
  "jungle": "جنگل",
  "plant": "پودا",
  "grass": "گھاس",
  "leaf": "پتا",
  "root": "جڑ",
  "seed": "بیج",
  "fruit": "پھل",
  "vegetable": "سبزی",
  "crop": "فصل",
  "zoo": "چڑیا گھر",
  "pet": "پالتو جانور",
  "horse": "گھوڑا",
  "cow": "گائے",
  "pig": "سور",
  "sheep": "بھیڑ",
  "goat": "بکری",
  "chicken": "مرغی",
  "snake": "سانپ",
  "lion": "شیر",
  "tiger": "بگھیر",
  "elephant": "ہاتھی",
  "bear": "ریچھ",
  "wolf": "بھیڑیا",
  "fox": "لومڑی",
  "rabbit": "خرگوش",
  "mouse": "چوہا",
  "rat": "چوہا",
  "insect": "کیڑا",
  "bug": "کیڑا",
  "fly": "مکھی",
  "mosquito": "مچھر",
  "bee": "شہد کی مکھی",
  "butterfly": "تتلی",
  "spider": "مکڑی",
  "population": "آبادی",
  "citizen": "شہری",
  "resident": "رہائشی",
  "neighbor": "پڑوسی",
  "stranger": "اجنبی",
  "guest": "مہمان",
  "visitor": "ملاقاتی",
  "student": "طالب علم",
  "teacher": "استاد",
  "professor": "پروفیسر",
  "doctor": "ڈاکٹر",
  "nurse": "نرس",
  "lawyer": "وکیل",
  "judge": "جج",
  "police": "پولیس",
  "officer": "افسر",
  "soldier": "فوجی",
  "employee": "ملازم",
  "employer": "آجر",
  "boss": "باس",
  "manager": "منیجر",
  "director": "ڈائریکٹر",
  "president": "صدر",
  "leader": "رہنما",
  "chief": "چیف",
  "captain": "کپتان",
  "driver": "ڈرائیور",
  "pilot": "پائلٹ",
  "cook": "باورچی",
  "chef": "شیف",
  "waiter": "ویٹر",
  "artist": "فنکار",
  "musician": "موسیقار",
  "singer": "گلوکار",
  "actor": "اداکار",
  "actress": "اداکارہ",
  "poet": "شاعر",
  "journalist": "صحافی",
  "reporter": "رپورٹر",
  "photographer": "فوٹوگرافر",
  "scientist": "سائنسدان",
  "researcher": "محقق",
  "engineer": "انجینئر",
  "architect": "معمار",
  "designer": "ڈیزائنر",
  "programmer": "پروگرامر",
  "developer": "ڈویلپر",
  "technician": "تکنیشن",
  "mechanic": "مکینک",
  "electrician": "بجلی کا کاریگر",
  "plumber": "پلمبر",
  "carpenter": "بڑھئی",
  "builder": "تعمیراتی کارکن",
  "farmer": "کسان",
  "gardener": "مالی",
  "fisherman": "ماہی گیر",
  "hunter": "شکاری",
  "trader": "تاجر",
  "merchant": "تاجر",
  "seller": "بیچنے والا",
  "buyer": "خریدنے والا",
  "consumer": "صارف",
  "user": "صارف",
  "owner": "مالک",
  "tenant": "کرایہ دار",
  "landlord": "مکان مالک",
  "host": "میزبان",
  "enemy": "دشمن",
  "rival": "حریف",
  "competitor": "مدمقابل",
  "partner": "ساتھی",
  "colleague": "ساتھی",
  "teammate": "ٹیم کا ساتھی",
  "classmate": "ہم جماعت",
  "roommate": "کمرے کا ساتھی",
  "relative": "رشتہ دار",
  "parent": "والدین",
  "father": "والد",
  "mother": "والدہ",
  "son": "بیٹا",
  "daughter": "بیٹی",
  "brother": "بھائی",
  "sister": "بہن",
  "uncle": "چچا",
  "aunt": "پھوپھی",
  "cousin": "کزن",
  "grandfather": "دادا",
  "grandmother": "دادی",
  "grandchild": "پوتا",
  "husband": "شوہر",
  "wife": "بیوی",
  "couple": "جوڑا",
  "marriage": "شادی",
  "wedding": "شادی",
  "divorce": "طلاق",
  "birth": "پیدائش",
  "funeral": "جنازہ",
  "celebration": "جشن",
  "party": "پارٹی",
  "festival": "تہوار",
  "ceremony": "تقریب",
  "event": "ایونٹ",
  "occasion": "موقع",
  "seminar": "سیمینار",
  "workshop": "ورکشاپ",
  "class": "کلاس",
  "lesson": "سبق",
  "course": "کورس",
  "library": "لائبریری",
  "museum": "میوزیم",
  "theater": "تھیٹر",
  "cinema": "سینما",
  "movie": "فلم",
  "film": "فلم",
  "performance": "کارکردگی",
  "game": "کھیل",
  "sport": "کھیل",
  "match": "میچ",
  "competition": "مقابلہ",
  "contest": "مقابلہ",
  "race": "دوڑ",
  "championship": "چیمپیئن شپ",
  "tournament": "ٹورنامنٹ",
  "league": "لیگ",
  "player": "کھلاڑی",
  "athlete": "کھلاڑی",
  "coach": "کوچ",
  "referee": "ریفری",
  "audience": "سامعین",
  "crowd": "بھیڑ",
  "fan": "پرستار",
  "supporter": "حامی",
  "ticket": "ٹکٹ",
  "seat": "نشست",
  "screen": "اسکرین",
  "display": "ڈسپلے",
  "monitor": "مانیٹر",
  "television": "ٹیلی ویژن",
  "tv": "ٹی وی",
  "radio": "ریڈیو",
  "song": "گانا",
  "fight": "لڑائی",
  "battle": "جنگ",
  "conflict": "تنازعہ",
  "treaty": "معاہدہ",
  "proposal": "تجویز",
  "suggestion": "تجویز",
  "recommendation": "سفارش",
  "warning": "انتباہ",
  "threat": "خطرہ",
  "task": "کام",
  "labor": "محنت",
  "pressure": "دباؤ",
  "stress": "دباؤ",
  "tension": "تناؤ",
  "worry": "پریشانی",
  "anxiety": "پریشانی",
  "fear": "خوف",
  "panic": "گھبراہٹ",
  "terror": "دہشت",
  "horror": "خوف",
  "shock": "صدمہ",
  "surprise": "حیرت",
  "wonder": "حیرت",
  "amazement": "حیرت",
  "confusion": "الجھن",
  "doubt": "شک",
  "uncertainty": "غیر یقینی",
  "matter": "معاملہ",
  "concept": "تصور",
  "notion": "تصور",
  "attitude": "رویہ",
  "model": "ماڈل",
  "sample": "نمونہ",
  "instance": "مثال",
  "village": "گاؤں",
  "neighborhood": "محلہ",
  "routine": "معمول",
  "schedule": "شیڈول",
  "timetable": "ٹائم ٹیبل",
  "calendar": "کیلنڈر",
  "date": "تاریخ",
  "decade": "دہائی",
  "century": "صدی",
  "age": "عمر",
  "period": "مدت",
  "era": "دور",
  "season": "موسم",
  "spring": "بہار",
  "summer": "گرمی",
  "autumn": "خزاں",
  "winter": "سردی",
  "soon": "جلد",
  "later": "بعد میں",
  "earlier": "پہلے",
  "following": "مندرجہ ذیل",
  "subsequent": "بعد میں",
  "prior": "پہلے",
  "updated": "اپ ڈیٹ",
  "revised": "نظرثانی شدہ",
  "improved": "بہتر",
  "enhanced": "بہتر",
  "advanced": "ایڈوانسڈ",
  "developed": "ترقی یافتہ",
  "evolved": "ارتقا یافتہ",
  "modified": "تبدیل شدہ",
  "altered": "تبدیل شدہ",
  "adjusted": "ایڈجسٹ شدہ",
  "adapted": "موافق",
  "customized": "حسب ضرورت",
  "personalized": "ذاتی",
  "proper": "مناسب",
  "appropriate": "مناسب",
  "suitable": "موزوں",
  "fitting": "موزوں",
  "relevant": "متعلقہ",
  "related": "متعلقہ",
  "connected": "جڑا ہوا",
  "linked": "جڑا ہوا",
  "associated": "وابستہ",
  "attached": "منسلک",
  "joined": "جڑا ہوا",
  "combined": "ملا ہوا",
  "united": "متحد",
  "together": "ساتھ",
  "separate": "الگ",
  "apart": "الگ",
  "divided": "تقسیم",
  "split": "تقسیم",
  "destroyed": "تباہ",
  "ruined": "برباد",
  "wrecked": "برباد",
  "missing": "گمشدہ",
  "gone": "چلا گیا",
  "disappeared": "غائب",
  "vanished": "غائب",
  "secret": "خفیہ",
  "confidential": "خفیہ",
  "classified": "خفیہ",
  "restricted": "محدود",
  "limited": "محدود",
  "controlled": "کنٹرول شدہ",
  "managed": "منظم",
  "organized": "منظم",
  "arranged": "منظم",
  "planned": "منصوبہ بند",
  "prepared": "تیار",
  "accessible": "قابل رسائی",
  "reachable": "پہنچ",
  "obtainable": "حاصل",
  "achievable": "قابل حصول",
  "feasible": "قابل عمل",
  "realistic": "حقیقت پسندانہ",
  "reasonable": "معقول",
  "logical": "منطقی",
  "rational": "عقلی",
  "sensible": "عقل مند",
  "brilliant": "شاندار",
  "genius": "جینیس",
  "talented": "ہونہار",
  "gifted": "ہونہار",
  "capable": "قابل",
  "able": "قابل",
  "competent": "اہل",
  "specialist": "ماہر"
};

export async function translateToUrdu(text: string): Promise<string> {
  let translated = text;
  
  for (const [english, urdu] of Object.entries(urduDictionary)) {
    const regex = new RegExp(`\\b${english}\\b`, 'gi');
    translated = translated.replace(regex, urdu);
  }
  
  return translated;
}