export const urduDictionary = {
  inspire: "حوصلہ افزائی",
  success: "کامیابی",
  achieve: "حاصل کرنا",
  learn: "سیکھنا",
  goal: "ہدف",
  dream: "خواب",
  effort: "کوشش",
  challenge: "چیلنج",
  motivation: "تحریک",
  progress: "ترقی",
  opportunity: "موقع",
  knowledge: "علم",
  skill: "ہنر",
  work: "کام",
  passion: "جذبہ",
  believe: "یقین",
  grow: "بڑھنا",
  strength: "طاقت",
  focus: "توجہ",
  vision: "تصور",
  change: "تبدیلی",
  future: "مستقبل",
  improve: "بہتر کرنا",
  create: "تخلیق کرنا",
  idea: "خیال",
  plan: "منصوبہ",
  action: "عمل",
  result: "نتیجہ",
  team: "ٹیم",
  lead: "قیادت کرنا",
  support: "حمایت",
  trust: "اعتماد",
  value: "قدر",
  respect: "احترام",
  share: "بانٹنا",
  connect: "جڑنا",
  build: "بنाना",
  innovate: "اختراع کرنا",
  solve: "حل کرنا",
  problem: "مسئلہ",
  solution: "حل",
  think: "سوچنا",
  understand: "سمجھنا",
  communicate: "بات چیت کرنا",
  listen: "سننا",
  speak: "بولنا",
  write: "لکھنا",
  read: "پڑھنا",
  explore: "دریافت کرنا",
  discover: "تلاش کرنا",
  journey: "سفر",
  experience: "تجربہ",
  wisdom: "دانائی",
  courage: "ہمت",
  hope: "امید",
  love: "محبت",
  life: "زندگی",
  happiness: "خوشی",
  peace: "امن",
  freedom: "آزادی",
  truth: "سچائی",
  power: "طاقت",
  energy: "توانائی",
  time: "وقت",
  world: "دنیا",
  people: "لوگ",
  community: "برادری",
  culture: "ثقافت",
  tradition: "روایت",
  history: "تاریخ",
  nature: "فطرت",
  environment: "ماحول",
  technology: "ٹیکنالوجی",
  science: "سائنس",
  data: "ڈیٹا",
  information: "معلومات",
  system: "نظام",
  process: "عمل",
  develop: "ترقی کرنا",
  design: "ڈیزائن",
  project: "منصوبہ",
  task: "کام",
  strategy: "حکمت عملی",
  failure: "ناکامی",
  quality: "معیار",
  performance: "کارکردگی",
  efficiency: "کارکردگی",
  effective: "مؤثر",
  impact: "اثر",
  growth: "ترقی",
  innovation: "اختراع",
  creativity: "تخلیقی صلاحیت",
  mission: "مشن",
  purpose: "مقصد",
  collaboration: "تعاون",
  teamwork: "ٹیم ورک",
  leadership: "قیادت",
  management: "انتظام",
  execute: "عمل کرنا",
  dedication: "لگن",
  commitment: "عزم",
  encourage: "حوصلہ دینا",
  help: "مدد",
  talent: "صلاحیت",
  ability: "قابلیت",
  weakness: "کمزوری",
  threat: "خطرہ",
  risk: "خطرہ",
  safety: "حفاظت",
  security: "سلامتی",
  confidence: "اعتماد",
  belief: "یقین",
  faith: "ایمان",
  aspiration: "خواہش",
  target: "ہدف",
  objective: "مقصد",
  step: "قدم",
  development: "ترقی",
  improvement: "بہتری",
  achievement: "کامیابی",
  victory: "فتح",
  obstacle: "رکاوٹ",
  answer: "جواب",
  question: "سوال",
  thought: "خیال",
  concept: "تصور",
  imagination: "تخیل",
  invention: "ایجاد",
  discovery: "دریافت",
  exploration: "تحقیق",
  research: "تحقیق",
  study: "مطالعہ",
  education: "تعلیم",
  intelligence: "ذہانت",
  practice: "مشق",
  job: "ملازمت",
  career: "کیریئر",
  profession: "پیشہ",
  business: "کاروبار",
  industry: "صنعت",
  market: "مارکیٹ",
  product: "پروڈکٹ",
  service: "سروس",
  customer: "صارف",
  client: "کلائنٹ",
  user: "صارف",
  society: "معاشرہ",
  honor: "عزت",
  dignity: "وقار",
  winner: "فتح یاب",
  couple: "جوڑا",
  island: "جزیرہ",
  season: "موسم",
  finale: "اختتام",
  vote: "ووٹ",
  prize: "انعام",
  cash: "نقد",
  connection: "رابطہ",
  dramatic: "ڈرامائی",
  conclusion: "نتیجہ",
  "runner-up": "دوسرے نمبر پر",
  place: "مقام",
  celebrate: "جشن منانا",
  zoomies: "جوشیلا دوڑنا",
  pool: "تالاب",
  summer: "موسم گرما",
  feel: "محسوس کرنا",
  powerful: "طاقتور",
  ride: "سفر",
  validated: "تصدیق شدہ",
  misunderstood: "غلط فہمی",
  scary: "خوفناک",
  good: "اچھا",
  superstar: "سپر سٹار",
  moment: "لمحہ",
  delivered: "پہنچایا",
  mattered: "اہمیت رکھتا",
  scoring: "گول کرنا",
  final: "اختتامی",
  thrashing: "زبردست شکست",
  games: "کھیل",
  club: "کلب",
  started: "شروع کیا",
  campaign: "مہم",
  appearances: "پیشیاں",
  glance: "نظر",
  underlying: "بنیادی",
  numbers: "اعداد",
  left: "چھوڑ دیا",
  barren: "بنجر",
  moments: "لمحات",
  involved: "شامل",
  attacking: "حملہ آور",
  sequences: "تسلسل",
  shots: "شاٹس",
  chances: "مواقع",
  created: "تخلیق کیا",
  pass: "پاس",
  "shot-ending": "شاٹ ختم کرنے والا",
  sequence: "تسلسل",
  confusion: "الجھن",
  form: "شکل",
  expected: "متوقع",
  identical: "یکساں",
  seasons: "مواسم",
  output: "پیداوار",
  match: "میچ",
  perspective: "نقطہ نظر",
  crucial: "اہم",
  outlined: "وضاحت کی",
  interview: "انٹرویو",
  talisman: "تعویذ",
  country: "ملک",
  manager: "منتظم",
  find: "تلاش کرنا",
  starting: "شروع",
  chief: "چیف",
  artists: "فنکار",
  title: "عنوان",
  crowd: "ہجوم",
  tourists: "سیاح",
  wriggle: "ہلنا",
  bodies: "جسم",
  space: "جگہ",
  defence: "دفاع",
  dispatched: "بھیجا",
  side: "طرف",
  attack: "حملہ",
  drifting: "بہنا",
  exploit: "استحصال کرنا",
  chink: "دراڑ",
  armour: "زِرہ",
  selfless: "بے لوث",
  running: "دوڑ",
  striker: "سٹرائیکر",
  integral: "لازمی",
  punishing: "سزا دینے والا",
  overload: "زیادہ بوجھ",
  area: "علاقہ",
  runs: "دوڑتا ہے",
  consistently: "مسلسل",
  found: "مل گیا",
  goalkeeper: "گول کیپر",
  receive: "وصول کرنا",
  cutbacks: "کٹ بیک",
  excellently: "شاندار طور پر",
  selection: "انتخاب",
  stretch: "کھینچنا",
  line: "لائن",
  "counter-attack": "جوابی حملہ",
  credit: "کریڈٹ",
  overlapping: "اوورلیپنگ",
  run: "دوڑنا",
  tension: "تناؤ",
  mind: "ذہن",
  extra: "اضافی",
  "half-a-beat": "آدھا دھڑکن",
  allowed: "اجازت دی",
  passing: "پاسنگ",
  bottom: "نیچے",
  corner: "کونہ",
  ice: "برف",
  veins: "رگیں",
  priority: "ترجیح",
  accurate: "درست",
  technique: "تکنیک",
  direct: "براہ راست",
  needle: "سوئی",
  assist: "مدد",
  special: "خاص",
  finishes: "ختم کرتا ہے",
  picked: "چنا",
  driving: "چلانا",
  forward: "آگے",
  thread: "دھاگہ",
  "perfectly-weighted": "بالکل وزن والا",
  impressive: "متاثر کن",
  individual: "انفرادی",
  reminiscent: "یاد دلانے والا",
  took: "لیا",
  matters: "معاملات",
  hands: "ہاتھ",
  scoop: "سکوپ",
  player: "کھلاڑی",
  award: "ایوارڈ",
  contributions: "شراکتیں",
  finals: "فائنلز",
  played: "کھیلا",
  progressive: "ترقی پسند",
  carries: "لے جاتا ہے",
  day: "دن",
  truly: "واقعی",
  worthy: "لائق",
  tournament: "ٹورنامنٹ",
  awards: "ایوارڈز",
  obliged: "پابند",
  accept: "قبول کرنا",
  unassuming: "بے تکلف",
  comfortable: "آرام دہ",
  quick: "تیز",
  kickabout: "فٹ بال کھیلنا",
  "confetti-strewn": "کنفیٹی سے بھرا",
  pitch: "پچ",
  squad: "ٹیم",
  young: "نوجوان",
  family: "خاندان",
  members: "ارکان",
  evening: "شام",
  short: "مختصر",
  clip: "کلپ",
  made: "بنایا",
  social: "سماجی",
  media: "میڈیا",
  man: "آدمی",
  hood: "ہڈ",
  riding: "سواری",
  scooter: "سکوٹر",
  noticed: "نوٹ کیا",
  weaving: "بُننا",
  iconic: "آئیکونک",
  landmark: "نشان",
  golden: "سنہری",
  ball: "گیند",
  best: "بہترین",
  cup: "کپ",
  barely: "بمشکل",
  hours: "گھنٹوں",
  normal: "عام",
  wants: "چاہتا ہے",
  play: "کھیلنا",
  football: "فٹ بال",
  manner: "انداز",
  dominated: "غلبہ کیا",
  champions: "چیمپئنز",
  rapidly: "تیزی سے",
};

export async function translateToUrdu(text: string): Promise<string> {
  let translated = text;
  for (const [en, ur] of Object.entries(urduDictionary)) {
    translated = translated.replace(new RegExp(`\\b${en}\\b`, "gi"), ur);
  }
  return translated;
}